header:
  version: 9

distro: poky

defaults:
  repos:
    refspec: master

repos:
  meta-trustedsubstrate:
    path: meta-trustedsubstrate
  poky:
    url: https://git.yoctoproject.org/git/poky
    layers:
      meta:
      meta-poky:
    patches:
      p1:
        repo : poky
        path : ../patches/0001-wic-add-UEFI-kernel-as-UEFI-stub.patch
      p2:
        repo : poky
        path : ../patches/0002-wic-bootimg-efi-implement-include-path.patch
  meta-arm:
    url: git://git.yoctoproject.org/meta-arm
    layers:
      meta-arm:
      meta-arm-bsp:
      meta-arm-toolchain:

env:
  BB_LOGCONFIG: ""
  TOOLCHAIN_DIR: ""
  UEFI_CERT_FILE: "${TOPDIR}/../meta-trustedsubstrate/uefi-certificates/uefi_certs.tgz"

local_conf_header:
  base: |
    CONF_VERSION = "2"
    PACKAGE_CLASSES = "package_ipk"
    LICENSE_FLAGS_WHITELIST += "armcompiler Arm-FVP-EULA"
    PACKAGECONFIG:remove:pn-qemu-system-native = "gtk+ sdl"
    EXTRA_IMAGE_FEATURES:append = " debug-tweaks"
    BB_NUMBER_THREADS = "16"
    PARALLEL_MAKE = "-j16"
    INHERIT += "rm_work"
    PACKAGECONFIG:append:pn-perf = " coresight"
  noptest: |
    DISTRO_FEATURES:remove = "ptest"
  sstate_mirror: |
    BB_HASHSERVE_UPSTREAM = "typhoon.yocto.io:8687"
    BB_HASHSERVE = "auto"
    BB_SIGNATURE_HANDLER = "OEEquivHash"

machine: unset

target:
  - ts-firmware
